import { Octokit } from '@octokit/rest';
import { createAppAuth } from '@octokit/auth-app';

const MAX_DIFF_SIZE = 15 * 1024; // 15KB
const IGNORED_PATTERNS = ['node_modules', 'build', 'dist', '.next', 'coverage', '*.min.js', '*.lock'];

function shouldIgnoreFile(filename: string): boolean {
  return IGNORED_PATTERNS.some(pattern => {
    if (pattern.startsWith('*.')) {
      return filename.endsWith(pattern.slice(1));
    }
    return filename.includes(pattern);
  });
}

async function getInstallationOctokit(installationId: number): Promise<Octokit> {
  const privateKey = process.env.GITHUB_PRIVATE_KEY!.replace(/\\n/g, '\n');

  const octokit = new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: process.env.GITHUB_APP_ID!,
      privateKey: privateKey,
      installationId: installationId,
    },
  });

  return octokit;
}

export async function fetchPRDiff(
  owner: string,
  repo: string,
  prNumber: number,
  installationId: number
): Promise<string> {
  try {
    const octokit = await getInstallationOctokit(installationId);
    const { data: files } = await octokit.pulls.listFiles({
      owner,
      repo,
      pull_number: prNumber,
    });

    let diffContent = '';

    for (const file of files) {
      if (shouldIgnoreFile(file.filename)) {
        continue;
      }

      if (file.patch) {
        const fileSection = `\n### ${file.filename} (${file.changes} changes)\n\`\`\`diff\n${file.patch}\n\`\`\``;

        if ((diffContent + fileSection).length > MAX_DIFF_SIZE) {
          diffContent += '\n\n... (diff truncated due to size) ...';
          break;
        }

        diffContent += fileSection;
      }
    }

    return diffContent;
  } catch (error) {
    console.error('Error fetching PR diff:', error);
    throw error;
  }
}

export async function postReviewToGitHub(
  owner: string,
  repo: string,
  prNumber: number,
  review: string,
  installationId: number
): Promise<void> {
  try {
    const octokit = await getInstallationOctokit(installationId);

    const maxCommentLength = 65536;
    let comment = review;

    if (review.length > maxCommentLength) {
      comment = review.substring(0, maxCommentLength - 100) + '\n\n... (review truncated) ...';
    }

    const botComment = `## 🤖 AI Code Review\n\n${comment}\n\n---\n*This review was generated by Claude AI.*`;

    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: botComment,
    });
  } catch (error) {
    console.error('Error posting review to GitHub:', error);
    throw error;
  }
}
